version: 0.0
os: linux
files:
  - source: /index.js
    destination: /home/ec2-user/app/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 30000
      runas: root
    - location: scripts/start_server
      timeout: 1000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 3000
      runas: root

