#!/bin/bash
sudo yum -y update
sudo yum -y install ruby
sudo yum -y install wget
cd /home/ec2-user
mkdir app
cd app
wget https://github-iot-socket-repo.s3.ap-south-1.amazonaws.com/iot-socket.zip
unzip iot-socket.zip
sudo su
curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash
sudo yum install -y nodejs
npm install
npm install -g pm2
sudo su
pm2 kill
