#!/bin/bash
# isExistPm2 = `pm2 stop app`
# if [[ -n  $isExistPm2 ]]; then
#     pm2 stop app
#     pm2 delete app
#     sudo su 
#     pm2 stop app
#     pm2 delete app
# fi

sudo su
pm2 list
pm2 stop 0
pm2 restart 0
pm2 kill 0