#!/bin/bash
# isExistPm2 = `pm2 stop app`
# if [[ -n  $isExistPm2 ]]; then
#     pm2 stop app
#     pm2 delete app
#     sudo su 
#     pm2 stop app
#     pm2 delete app
# fi
sudo su
npm uninstall -g pm2
#sudo su
#pm2 kill